### ISSUE TITLE
Scoping Watchdog service & default unique one support

### ISSUE THREAD

**Issue by raneomik** [raneomik/WatchdogBundle#3]
Currently, it supports a unique default watchdog config, under `dates` config key. 

It would be nice if applications could embed, if needed, dynamicaly named Watchdog like this : 

for example, giving this configuration : 

```yml

watchdog:
    maintance: 
    - { relative: 'mondays' }
    weekend:
    - compound : 
        - { relative: 'saturdays' }
        - { relative: 'sundays' }
```

it should provide those Watchdog services : 

```php

class Service
{
     __construct(
        private Watchdog $maintenanceWatchdog,
        private Watchdog $weekendWatchdog
    ) {
   }
....
```
where each of those watchdogs have their independent time configuration.

Needs adaptations on provided handler & the handling subscriber.

Occasionnaly, make a WatchdogInterface to impose method signatures & leverage code coupling (and then permitting fakes / dummies / stubs / own logics).

Also, maybe flexibilise the config to support a unique defautlt wathdog as follows : 

```yml
watchdog:
    - { relative: 'mondays' }
```

providing this unique service : 

```php

class Service
{
     __construct(
        private WatchdogInterface $watchdog
    ) {
   }
....
```
